AWSTemplateFormatVersion: "2010-09-09"

Description: "AWS Monthly Budget Notification"

Parameters:
  Email:
    Type: String
    Description: "Email address to receive budget notifications"

Resources:
  MyMonthlyBudget:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: !Sub "monthly-budget-${AWS::StackName}"
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: 5
          Unit: USD
      NotificationsWithSubscribers:
        # Notificación al 40% del gasto REAL (2 USD)
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 40
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
        # Notificación al 80% del gasto REAL (4 USD)
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
        # Notificación al 80% del gasto PRONOSTICADO (Forecasted)
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
